### ISSUE TITLE
Problem to generate files at it is.

### ISSUE THREAD

**Issue by vega0** [SomeRanDev/reflaxe#10]
By default reflaxe creates separately objects into multiple files. It is possible to get information about imports and packages? 
It is possible to create file metadata info to assembly anything from one file into one file. ?

**Comment by vega0** [comment]
is it possible to determine the type of "if" definition as normal and ternary.

**Comment by RobertBorghese** [comment]
Reflaxe does have the ability to output files manually if you'd prefer that! In my Reflaxe/C++ project, I return `null` for the compileClass/Enum functions so they don't generate anything automatically. https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/subcompilers/Classes.hx#L318C9-L318C9

Instead, I store the output in an array. Using the `BaseCompiler.onCompileEnd` function (https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/Compiler.hx#L176C5-L176C5), I can then output everything manually using the `BaseCompiler.appendToExtraFile(filename: String, output: String)`.

In Reflaxe/C++ specifically, I use `BaseCompiler.addCompileEndCallback` at the end of generating the class to do this, but you don't have to. https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/subcompilers/Classes.hx#L1165C3-L1165C3

**Comment by vega0** [comment]
is it possible to recognize 'if' is ternary or not?

**Comment by vega0** [comment]
is it possible to get import instructions of file ?

**Comment by vega0** [comment]
> Reflaxe does have the ability to output files manually if you'd prefer that! In my Reflaxe/C++ project, I return `null` for the compileClass/Enum functions so they don't [generate anything automatically](https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/subcompilers/Classes.hx#L318C9-L318C9).
> 
> Instead, I store the output in an array. Using the `BaseCompiler.onCompileEnd` [function](https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/Compiler.hx#L176C5-L176C5), I can then output everything manually using the `BaseCompiler.appendToExtraFile(filename: String, output: String)`.
> 
> In Reflaxe/C++ specifically, I use `BaseCompiler.addCompileEndCallback` [at the end of generating the class](https://github.com/RobertBorghese/reflaxe.CPP/blob/e537b3b22032b69105054a503290ae559c9c055a/src/cxxcompiler/subcompilers/Classes.hx#L1165C3-L1165C3) to do this, but you don't have to.

two questing above.

**Comment by SomeRanDev** [comment]
Sorry for missing your two questions. If you have any general questions, I would highly recommend asking in the "Reflaxe" project forum on the [Haxe Discord server](https://discord.com/channels/162395145352904705/1052688097592225904).

> is it possible to recognize 'if' is ternary or not?

I'm afraid not, this is a limitation built into the Haxe compiler.

> is it possible to get import instructions of file ?

The Haxe compiler does not provide this information; you have to keep track of which classes are used in a module and create the imports yourself.
