### ISSUE TITLE
Using macros in std possible?

### ISSUE THREAD

**Issue by neimanpinchas** [SomeRanDev/reflaxe#23]
While working on my golang target, I tried to make a macro to make my life easy with converting mutireturuns into throws.

So far haxe complains about not finding the macros

sys.io.File
```haxe
package sys.io;

#if macro
import gostd.LangMacros.go2exception;
#end
class File {
    public static function getContent(fn:String) {
        return go2exception(gostd.Os.ReadFile(fn));
    }
    public static function saveContent(fn:String,content:String) {
        return go2exception(gostd.Os.ReadFile(fn));
    }
    //#if macro
    public static  macro function go2exception(func:Expr):Expr {
        return macro  {
            var stati = $func;
                    if (stati.err!=null){
                        throw stati.err;
                    } else {
                        return stati.db;
                        };
                    }
        
    }
    //#end
}
```

gostd/Os.hx
```haxe
@:native("os")
extern class Os {
    extern static function ReadFile(p:String):Duet<gostd.Io.IoReader,Exception>;
    extern static function WriteFile(p:String,d:gostd.Io.IoReader):String;
}

@:multiReturn class Duet<T1,T2> {
    public var db:T1;
    public var err:T2;
}

```

Is it related with https://haxe.org/manual/macro-limitations-macro-in-macro.html given the reflaxe compiler is also working in the macro context?

**Comment by SomeRanDev** [comment]
No, Reflaxe should not prevent your use of macros in your general code. Haxe macros can be a bit finicky, so I'm not 100% sure why this is happening, but it should work. Could you try moving the macro function to a different file and using it from there?

**Comment by neimanpinchas** [comment]
In fact I moved them into the file to counter the not found disorder, initialy they were in a diffrent file.

Maybe it has to do with the way Haxe combines all levels of std (I am still confused with this part)

I will think what I can figure out.

I think we can close this ticket if it is not reflaxe related.
