### ISSUE TITLE
Module haxe.macro.Compiler does not define type MetadataDescription

### ISSUE THREAD

**Issue by sonygod** [SomeRanDev/reflaxe#24]
Following your Unreal Engine and Haxe sample project, I tried to build the latest version of UE 5.4. Then, I executed:

```
haxe compile.hxml
```

And received the following error:

```
E:\unreal_project\Haxe-UnrealEngine5\SampleProject\Haxe\.haxelib\reflaxe/git/src/reflaxe/BaseCompiler.hx:369: characters 9-48 : Module haxe.macro.Compiler does not define type MetadataDescription
```

Haxe is using your custom version available at https://github.com/SomeRanDev/evil-haxe/releases.

**Comment by SomeRanDev** [comment]
Sorry for the delay, Reflaxe does not support any versions of Haxe below 4.3 (`MetadataDescription` was added in Haxe v4.3). Sorry about Evil Haxe being at 4.2, I have no plans to maintain or update it at the moment, sorry! >,<
