### ISSUE TITLE
Error "macro in macro" When Accessing Compiler Defines Using `Compiler.getVariable`

### ISSUE THREAD

**Issue by neimanpinchas** [SomeRanDev/reflaxe#26]
**Description:**
When attempting to access compiler defines using `Compiler.getDefine`, I encounter an error: "macro in macro". 

I need it to control various compilation options for example package name,

What is the recommended way to do it from reflaxe?

**Comment by SomeRanDev** [comment]
It's a little annoying, but you might need to wrap it with `#if macro`, that's what I do in Reflaxe/C++:
https://github.com/SomeRanDev/reflaxe.CPP/blob/0630b5824b5574e368d622c37588b70869d312af/src/cxxcompiler/CompilerInit.hx#L55

**Comment by neimanpinchas** [comment]
Fixed the issue and added 2 new defines.

My real isue was that I've been stupid and used `Cmpiler.getDefine` instead of  `Context.definedValue`, your link was in context in either case, and pinpointed where I was wrong.


Thank you
