### ISSUE TITLE
The other question.

### ISSUE THREAD

**Issue by vega0** [SomeRanDev/reflaxe#5]
After creating reflaxe transpille. f.e. haxe to moonscript, how i can just add it to main project as generator?
Another question, how to make reflaxe works as single file builder output? (standalone file project generator.)

**Comment by RobertBorghese** [comment]
I'm sorry, I'm a little confused by the questions. So sorry if these are not the answers you are looking for.

---

To generate the library, run:
```
haxelib run reflaxe build
```
In the directory of your Reflaxe project. Then use the `_Build` folder as a library in another Haxe project (you can submit to haxelib or use `haxelib dev`)

---

To have the output be a single file, modify the "fileOutputType" option.
