### ISSUE TITLE
make middle processor for all build target results 

### ISSUE THREAD

**Issue by vega0** [SomeRanDev/reflaxe#6]
make middle processor for all build target results to implement obfuskation, is it possible?

**Comment by RobertBorghese** [comment]
Sorry, I'm confused about the question again. 😅 Are you asking if Reflaxe can be used to process the output of existing Haxe targets? If so, I'm afraid not. You could probably find a way to obfuscate the output from Haxe by using a script in a `.hxml` file, but you'll need to ask about that more on the Haxe forums or Discord.
